name: Docker Compose Build test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker:
    name: Docker run
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - run: docker compose build
