name: Go CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          check-latest: true
          cache-dependency-path: | # not necessary if there is only one go.sum file at root
            go.sum

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - run: go vet
      - run: go run honnef.co/go/tools/cmd/staticcheck@latest ./...
      - run: go test ./...
      - run: go build .
      - run: gofmt
